#!/usr/bin/env bash
# ============================================================================
# HAM10000 cross-domain summary figure — three panels, one experiment. CPU-only.
#
# Joins two existing bootstrap reports; it never re-runs inference and never trains:
#   reports/external/ham10000/<variant>/bootstrap_ci.json -> per_run + kd_deltas
#   experiments/runs/bootstrap_ci.json                    -> in-domain per_run
#
# WHY THREE PANELS: Muc 4.7 of the thesis reports ONE experiment (every trained
# run scored, unchanged, on one out-of-domain set) but had grown four tables that
# each showed a slice of it.
#   (a) forest plot of the paired KD delta  -> did KD survive the domain change
#   (b) achieved score vs that delta        -> biggest gain != best score
#   (c) Sens@90%Spec in-domain vs on HAM    -> the operating point does not transfer
#
# Panel (c) fixes specificity at 90% on BOTH ends, so the threshold is already
# re-picked per domain; sensitivity still collapses. That is the evidence for
# "ranking capability was lost", not "the threshold drifted".
#
# BOTH inputs must come from the SAME evaluation round. `bootstrap_ci.json` is
# regenerated by run/bootstrap_ci.sh; if the external eval is re-run, re-run the
# CIs for both dirs before redrawing, or the two ends of panel (c) disagree.
#
# Args are KEY=VALUE OR env vars:
#   HAM_CI       external bootstrap report
#                (default reports/external/ham10000/headline/bootstrap_ci.json)
#   INDOMAIN_CI  in-domain bootstrap report (default experiments/runs/bootstrap_ci.json)
#   METRIC       ranking metric for (a) and (b)   (default auprc)
#   OP_METRIC    operating point for (c)          (default sens_at_90spec)
#   OUT          output png; an .svg is written alongside
#                                                 (default reports/ham_summary.png)
#   DPI          raster resolution                (default 200)
#
# Usage:
#   bash run/plot_ham_summary.sh
#   bash run/plot_ham_summary.sh METRIC=pauc_at_tpr80 OUT=reports/ham_pauc.png
# ============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
for arg in "$@"; do export "${arg?}"; done

start_log "plot_ham_summary"
activate_venv
# Pure matplotlib over existing JSON — stays runnable while a job owns the GPU.
export CUDA_VISIBLE_DEVICES=""
export TMPDIR="${TMPDIR:-${PROJECT_DIR}/.tmp}"
export MPLCONFIGDIR="${TMPDIR}/mpl"
mkdir -p "${TMPDIR}" "${MPLCONFIGDIR}"

HAM_CI="${HAM_CI:-reports/external/ham10000/headline/bootstrap_ci.json}"
INDOMAIN_CI="${INDOMAIN_CI:-experiments/runs/bootstrap_ci.json}"
METRIC="${METRIC:-auprc}"
OP_METRIC="${OP_METRIC:-sens_at_90spec}"
OUT="${OUT:-reports/ham_summary.png}"
DPI="${DPI:-200}"

for f in "${HAM_CI}" "${INDOMAIN_CI}"; do
    if [ ! -s "${f}" ]; then
        echo "[run] ERROR: missing or empty input: ${f}" >&2
        echo "[run]   both come from run/bootstrap_ci.sh RESULTS_DIR=<dir>" >&2
        exit 2
    fi
done

echo "[run] HAM summary | ham=${HAM_CI} indomain=${INDOMAIN_CI} metric=${METRIC} op=${OP_METRIC} -> ${OUT}"
python scripts/plot_ham_summary.py \
    --ham-ci "${HAM_CI}" \
    --indomain-ci "${INDOMAIN_CI}" \
    --metric "${METRIC}" \
    --op-metric "${OP_METRIC}" \
    --out "${OUT}" \
    --dpi "${DPI}"

echo "[run] DONE"
